version: "2"

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"
  jobs:
    post_install:
      - pip install --no-build-isolation --no-deps -e .
  apt_packages:
    - graphviz

python:
  install:
    - requirements: requirements/build_requirements.txt
    - requirements: requirements/doc_requirements.txt

sphinx:
  configuration: ./docs/conf.py
  builder: dirhtml

formats:
  - pdf
