name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]


jobs:
  pre-commit:
    name: Pre-Commit
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.12 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - name: Get week number
        id: week
        run: echo "WEEK=$(date +'%V')" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: im_env
          create-args: >-
            python=${{ matrix.python-version }}
            --file requirements.txt
          cache-environment: true
          cache-environment-key: py${{ matrix.python-version }}-${{ matrix.os }}-W${{ env.WEEK }}-${{ hashFiles('requirements.txt') }}

      - name: Run pre-commit
        run: pre-commit run --all-files

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix pre-commit issues
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
